name: Publicar Imagen Docker

on:
  push:
    # Se activa con push a las ramas de desarrollo y producci칩n
    branches: [ "main", "dev" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # Define la etiqueta (tag) a usar en el registro
    env:
      # Si la rama es 'main', la etiqueta es 'latest'. Si no, usa el nombre de la rama.
      IMAGE_TAG: ${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
      IMAGE_NAME: ghcr.io/${{ github.repository }}

    permissions:
      contents: read
      packages: write # Permiso para publicar en GHCR

    steps:
      - name: Checkout del c칩digo
        uses: actions/checkout@v4

      - name: Iniciar sesi칩n en GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Token autom치tico de GitHub

      - name: Construir y publicar la imagen (CD)
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          # Usa la variable IMAGE_TAG definida arriba (latest o dev)
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          file: ./Dockerfile