name: CI

on:
  push:
    branches: [ main, develop, "**/feature/**" ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Spotless (formatter)
        run: ./gradlew spotlessCheck --no-daemon

      - name: Checkstyle (linter)
        run: ./gradlew checkstyleMain checkstyleTest --no-daemon

      - name: Build, Test & Coverage
        run: ./gradlew clean test jacocoTestReport --no-daemon

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html

      - name: Upload JUnit test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-results
          path: build/test-results/test